[package]
name = "rust_robotics"
version = "0.1.0"
authors = ["ryohei sasaki <rsasaki0109@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.4"
plotlib = "0.5.1"
rand = "0.8.5"
rand_distr = "0.4.3"
